// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : litesdcard_core.v
// Device     : 
// LiteX sha1 : 81b70d1
// Date       : 2024-06-15 18:36:43
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module litesdcard_core (
    input  wire          clk,
    output wire          irq,
    input  wire          rst,
    input  wire          sdcard_cd,
    output reg           sdcard_clk,
    inout  wire          sdcard_cmd,
    output reg           sdcard_cmd_dir,
    output reg           sdcard_dat0_dir,
    output reg           sdcard_dat13_dir,
    inout  wire    [3:0] sdcard_data,
    output wire          wb_ctrl_ack,
    input  wire   [29:0] wb_ctrl_adr,
    input  wire    [1:0] wb_ctrl_bte,
    input  wire    [2:0] wb_ctrl_cti,
    input  wire          wb_ctrl_cyc,
    output wire   [31:0] wb_ctrl_dat_r,
    input  wire   [31:0] wb_ctrl_dat_w,
    output wire          wb_ctrl_err,
    input  wire    [3:0] wb_ctrl_sel,
    input  wire          wb_ctrl_stb,
    input  wire          wb_ctrl_we,
    input  wire          wb_dma_ack,
    output wire   [29:0] wb_dma_adr,
    output wire    [1:0] wb_dma_bte,
    output wire    [2:0] wb_dma_cti,
    output wire          wb_dma_cyc,
    input  wire   [31:0] wb_dma_dat_r,
    output wire   [31:0] wb_dma_dat_w,
    input  wire          wb_dma_err,
    output wire    [3:0] wb_dma_sel,
    output wire          wb_dma_stb,
    output wire          wb_dma_we
);
endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-06-15 18:36:43.
//------------------------------------------------------------------------------
