// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : litedram_core.v
// Device     : 
// LiteX sha1 : 81b70d1
// Date       : 2024-06-15 18:21:38
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module litedram_core (
    input  wire          clk,
    output wire   [13:0] ddram_a,
    output wire    [2:0] ddram_ba,
    output wire          ddram_cas_n,
    output wire          ddram_cke,
    output wire          ddram_clk_n,
    output wire          ddram_clk_p,
    output wire          ddram_cs_n,
    output wire    [1:0] ddram_dm,
    inout  wire   [15:0] ddram_dq,
    inout  wire    [1:0] ddram_dqs_n,
    inout  wire    [1:0] ddram_dqs_p,
    output wire          ddram_odt,
    output wire          ddram_ras_n,
    output wire          ddram_reset_n,
    output wire          ddram_we_n,
    output wire          init_done,
    output wire          init_error,
    output wire          pll_locked,
    input  wire          rst,
    input  wire          uart_rx,
    output reg           uart_tx,
    output wire          user_clk,
    input  wire  [127:0] user_fifo_fifo_0_in_data,
    output wire          user_fifo_fifo_0_in_ready,
    input  wire          user_fifo_fifo_0_in_valid,
    output wire  [127:0] user_fifo_fifo_0_out_data,
    input  wire          user_fifo_fifo_0_out_ready,
    output wire          user_fifo_fifo_0_out_valid,
    input  wire   [23:0] user_port_avalon_0_address,
    input  wire    [7:0] user_port_avalon_0_burstcount,
    input  wire   [15:0] user_port_avalon_0_byteenable,
    input  wire          user_port_avalon_0_read,
    output wire  [127:0] user_port_avalon_0_readdata,
    output wire          user_port_avalon_0_readdatavalid,
    output wire          user_port_avalon_0_waitrequest,
    input  wire          user_port_avalon_0_write,
    input  wire  [127:0] user_port_avalon_0_writedata,
    input  wire   [27:0] user_port_axi_0_araddr,
    input  wire    [1:0] user_port_axi_0_arburst,
    input  wire   [31:0] user_port_axi_0_arid,
    input  wire    [7:0] user_port_axi_0_arlen,
    output wire          user_port_axi_0_arready,
    input  wire    [3:0] user_port_axi_0_arsize,
    input  wire          user_port_axi_0_arvalid,
    input  wire   [27:0] user_port_axi_0_awaddr,
    input  wire    [1:0] user_port_axi_0_awburst,
    input  wire   [31:0] user_port_axi_0_awid,
    input  wire    [7:0] user_port_axi_0_awlen,
    output wire          user_port_axi_0_awready,
    input  wire    [3:0] user_port_axi_0_awsize,
    input  wire          user_port_axi_0_awvalid,
    output wire   [31:0] user_port_axi_0_bid,
    input  wire          user_port_axi_0_bready,
    output wire    [1:0] user_port_axi_0_bresp,
    output wire          user_port_axi_0_bvalid,
    output wire  [127:0] user_port_axi_0_rdata,
    output wire   [31:0] user_port_axi_0_rid,
    output wire          user_port_axi_0_rlast,
    input  wire          user_port_axi_0_rready,
    output wire    [1:0] user_port_axi_0_rresp,
    output wire          user_port_axi_0_rvalid,
    input  wire  [127:0] user_port_axi_0_wdata,
    input  wire          user_port_axi_0_wlast,
    output wire          user_port_axi_0_wready,
    input  wire   [15:0] user_port_axi_0_wstrb,
    input  wire          user_port_axi_0_wvalid,
    input  wire   [23:0] user_port_native_0_cmd_addr,
    output wire          user_port_native_0_cmd_ready,
    input  wire          user_port_native_0_cmd_valid,
    input  wire          user_port_native_0_cmd_we,
    output wire  [127:0] user_port_native_0_rdata_data,
    input  wire          user_port_native_0_rdata_ready,
    output wire          user_port_native_0_rdata_valid,
    input  wire  [127:0] user_port_native_0_wdata_data,
    output wire          user_port_native_0_wdata_ready,
    input  wire          user_port_native_0_wdata_valid,
    input  wire   [15:0] user_port_native_0_wdata_we,
    output wire          user_port_wishbone_0_ack,
    input  wire   [23:0] user_port_wishbone_0_adr,
    input  wire          user_port_wishbone_0_cyc,
    output wire  [127:0] user_port_wishbone_0_dat_r,
    input  wire  [127:0] user_port_wishbone_0_dat_w,
    output wire          user_port_wishbone_0_err,
    input  wire   [15:0] user_port_wishbone_0_sel,
    input  wire          user_port_wishbone_0_stb,
    input  wire          user_port_wishbone_0_we,
    output wire          user_rst
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-06-15 18:21:39.
//------------------------------------------------------------------------------
