// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : litespi_core.v
// Device     : 
// LiteX sha1 : 81b70d1
// Date       : 2024-06-15 18:10:07
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module litespi_core_wishbone (
    output wire          bus_ack,
    input  wire   [29:0] bus_adr,
    input  wire    [1:0] bus_bte,
    input  wire    [2:0] bus_cti,
    input  wire          bus_cyc,
    output wire   [31:0] bus_dat_r,
    input  wire   [31:0] bus_dat_w,
    output wire          bus_err,
    input  wire    [3:0] bus_sel,
    input  wire          bus_stb,
    input  wire          bus_we,
    input  wire          clk,
    input  wire          rst,
    output reg           spiflash_clk,
    output wire          spiflash_cs_n,
    input  wire          spiflash_hold,
    input  wire          spiflash_miso,
    output reg           spiflash_mosi,
    input  wire          spiflash_wp
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-06-15 18:10:07.
//------------------------------------------------------------------------------
