// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : litesata_core.v
// Device     : xc7a
// LiteX sha1 : 81b70d1
// Date       : 2024-06-15 18:35:00
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module litesata_core (
    input  wire          clk,
    input  wire          enable,
    output wire          ready,
    input  wire          rst,
    input  wire          sata_clk_n,
    input  wire          sata_clk_p,
    input  wire          sata_rx_n,
    input  wire          sata_rx_p,
    output wire          sata_tx_n,
    output wire          sata_tx_p,
    input  wire   [15:0] user_port_native_0_sink_count,
    input  wire   [31:0] user_port_native_0_sink_data,
    input  wire          user_port_native_0_sink_identify,
    input  wire          user_port_native_0_sink_last,
    input  wire          user_port_native_0_sink_read,
    output wire          user_port_native_0_sink_ready,
    input  wire   [47:0] user_port_native_0_sink_sector,
    input  wire          user_port_native_0_sink_valid,
    input  wire          user_port_native_0_sink_write,
    output wire   [31:0] user_port_native_0_source_data,
    output wire          user_port_native_0_source_end,
    output wire          user_port_native_0_source_failed,
    output wire          user_port_native_0_source_identify,
    output wire          user_port_native_0_source_last,
    output wire          user_port_native_0_source_read,
    input  wire          user_port_native_0_source_ready,
    output wire          user_port_native_0_source_valid,
    output wire          user_port_native_0_source_write
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-06-15 18:35:00.
//------------------------------------------------------------------------------
