// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : liteeth_core.v
// Device     : 
// LiteX sha1 : 81b70d1
// Date       : 2024-06-15 18:30:03
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module liteeth_core (
    input  wire   [31:0] bus_araddr,
    input  wire    [2:0] bus_arprot,
    output wire          bus_arready,
    input  wire          bus_arvalid,
    input  wire   [31:0] bus_awaddr,
    input  wire    [2:0] bus_awprot,
    output wire          bus_awready,
    input  wire          bus_awvalid,
    input  wire          bus_bready,
    output wire    [1:0] bus_bresp,
    output wire          bus_bvalid,
    output wire   [31:0] bus_rdata,
    input  wire          bus_rready,
    output wire    [1:0] bus_rresp,
    output wire          bus_rvalid,
    input  wire   [31:0] bus_wdata,
    output wire          bus_wready,
    input  wire    [3:0] bus_wstrb,
    input  wire          bus_wvalid,
    output wire          interrupt,
    input  wire          mii_clocks_rx,
    input  wire          mii_clocks_tx,
    input  wire          mii_col,
    input  wire          mii_crs,
    output wire          mii_mdc,
    inout  wire          mii_mdio,
    output wire          mii_rst_n,
    input  wire    [3:0] mii_rx_data,
    input  wire          mii_rx_dv,
    input  wire          mii_rx_er,
    output reg     [3:0] mii_tx_data,
    output reg           mii_tx_en,
    input  wire          sys_clock,
    input  wire          sys_reset
);


endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-06-15 18:30:03.
//------------------------------------------------------------------------------
